version: '3.8'

services:
  mi-vitae:
    container_name: mi-vitae
    build:
      context: .
      dockerfile: Dockerfile
    image: mi-vitae:latest
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=mi-vitae.wearesamod.com
      - VIRTUAL_PORT=80
    networks:
      - samod-network

networks:
  samod-network:
    external: true
    name: samod-network
